"""remove members table

Revision ID: 54ef21c4f7f5
Revises: b10d0c01b384
Create Date: 2026-06-24 18:31:53.618276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54ef21c4f7f5"
down_revision: Union[str, Sequence[str], None] = "b10d0c01b384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_table("members")
    op.alter_column(
        "book_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "books", "available_quantity", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "issued_books", "request_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key(None, "issued_books", "book_requests", ["request_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issued_books", type_="foreignkey")
    op.alter_column(
        "issued_books", "request_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "books", "available_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "book_requests",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("members_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("members_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    # ### end Alembic commands ###
