"""add rent and deposit amount

Revision ID: 640af6c0ba8c
Revises: 1e83306de3a1
Create Date: 2026-06-26 12:40:32.101748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "640af6c0ba8c"
down_revision: Union[str, Sequence[str], None] = "1e83306de3a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "rent_per_day",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.add_column("issued_books", sa.Column("rent_amount", sa.Float(), nullable=True))
    op.add_column(
        "issued_books", sa.Column("deposit_amount", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issued_books", "deposit_amount")
    op.drop_column("issued_books", "rent_amount")
    op.alter_column(
        "books",
        "rent_per_day",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
