"""add fine fields

Revision ID: 9006a17a7972
Revises: 54ef21c4f7f5
Create Date: 2026-06-25 06:32:09.310810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9006a17a7972"
down_revision: Union[str, Sequence[str], None] = "54ef21c4f7f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issued_books", sa.Column("fine_amount", sa.Integer(), nullable=True))
    op.add_column("issued_books", sa.Column("fine_paid", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issued_books", "fine_paid")
    op.drop_column("issued_books", "fine_amount")
    # ### end Alembic commands ###
