"""Update chat models

Revision ID: c843c20179ad
Revises: 2de70a1ca234
Create Date: 2026-07-10 12:38:01.317311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c843c20179ad'
down_revision: Union[str, Sequence[str], None] = '2de70a1ca234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_chat_messages_chat_request_id'), 'chat_messages', ['chat_request_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_receiver_id'), 'chat_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_receiver_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_request_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
