"""Add deposit paid date

Revision ID: dafef7342901
Revises: b9f6a63e51c2
Create Date: 2026-07-09 11:53:16.419448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafef7342901'
down_revision: Union[str, Sequence[str], None] = 'b9f6a63e51c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_books', sa.Column('deposit_paid_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issued_books', 'deposit_paid_date')
    # ### end Alembic commands ###
